### ISSUE TITLE
why do u choose EhCache

### ISSUE THREAD

**Issue by HelloTo4x** [nasirov/anime-checker#2]
Hi, why do u choose EhCache for caching instead of other caches like Caffeine, redis... because i see Cafeine workes higher perfomance than Ehcache

**Comment by nasirov** [comment]
Hi, at the very beginning of the project, I didn't pay too much attention which cache to choose. I picked Ehcache because I used it before, didn't experience any issues, and it matched my preferences. Also, I wasn't sure which cache features I will use and since Ehcache provided wider range of the features It played a role. I see that Caffeine has higher performance and maybe now it fits better for the current cache needs of the project, but as I said before I didn't experience any issues yet, so I don't see a major reason in migration to Caffeine from Ehcache.

**Comment by HelloTo4x** [comment]
tk y
